services:
  bricktracker:
    container_name: BrickTracker
    restart: unless-stopped
    image: ghcr.io/tylerobara/tylerobara/bricktracker:master
    ports:
      - "3333:3333"
    volumes:
      - ${STATIC_DIR:-./}.:/app
    env_file:
      - .env
